# SETTINGS FOR THE WEBSITE SCRAPER
---
active-websites:
  newegg: True
  bestbuy: True
  bhphoto: False

search-options:
  limit-pages: 5 # For no limit set to 0 (0 by default)
  wait-time: 0 # Time to load between each page