# SETTINGS FOR THE WEBSITE SCRAPER
---
active-websites:
  newegg: True
  bestbuy: False

search-options:
  limit-pages: 0 # For no limit set to 0 (0 by default)
  max-items: 0 # For no limit set to 0
  wait-time: 0 # Time to load between each page