# SETTINGS FOR THE WEBSITE SCRAPER - CONFIG.YAML
---
active-websites:
  newegg: True  # True / False
  bestbuy: True # True / False

search-options:
  limit-pages: 5              # Limits amount of pages scanned (5 by default | 0 for no limit)
  wait-time: 0                # Time to load between each page (600 seconds is max | 0 by default for no limit)
  include-out-of-stock: False # Includes out of stock items (False by default)